# Generated by Django 6.0.3 on 2026-04-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('txt', 'TXT'), ('image', 'Image')], default='pdf', max_length=10),
        ),
    ]
