# Generated by Django 6.0.3 on 2026-09-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_conversation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
